############################################################
# Module Auto-Aggregation Script (DRAFT)
#
# Scans for module.json manifests and generates:
# - _auto-includes.pug (top-level structure)
# - allstyles.styl (style imports)
# - Copies worker files to public directory
#
# Usage: coffee aggregate-modules.coffee [--dry-run]
#
# Status: DRAFT - not yet tested
############################################################

fs = require 'fs'
path = require 'path'

############################################################
#region Configuration

# Paths relative to project root - adjust as needed
CONFIG =
    projectRoot: path.resolve(__dirname, '../../../..')
    modulesDir: 'sources/source'
    outputDir: 'sources/source/allmodules'
    indexDir: 'sources/source/index'
    publicDir: 'public'  # or wherever static assets go
    manifestName: 'module.json'

#endregion

############################################################
#region Helpers

# Find all module.json files in modules directory
findManifests = ->
    modulesPath = path.join(CONFIG.projectRoot, CONFIG.modulesDir)
    entries = fs.readdirSync(modulesPath, { withFileTypes: true })

    manifests = []
    for entry in entries when entry.isDirectory() and entry.name.endsWith('module')
        manifestPath = path.join(modulesPath, entry.name, CONFIG.manifestName)
        if fs.existsSync(manifestPath)
            try
                content = fs.readFileSync(manifestPath, 'utf8')
                manifest = JSON.parse(content)
                manifest._dir = entry.name  # Store directory name for reference
                manifests.push(manifest)
            catch err
                console.error "Error reading #{manifestPath}: #{err.message}"

    return manifests

# Ensure directory exists
ensureDir = (dirPath) ->
    unless fs.existsSync(dirPath)
        fs.mkdirSync(dirPath, { recursive: true })

#endregion

############################################################
#region Generators

# Generate allstyles.styl content
generateStyles = (manifests) ->
    lines = [
        '// Auto-generated by aggregate-modules.coffee'
        '// Do not edit manually - changes will be overwritten'
        ''
    ]

    for m in manifests when m.assets?.styles
        lines.push "@import '../#{m._dir}/#{m.assets.styles}'"

    return lines.join('\n') + '\n'

# Generate _auto-includes.pug content
generateStructure = (manifests) ->
    lines = [
        '//- Auto-generated by aggregate-modules.coffee'
        '//- Do not edit manually - changes will be overwritten'
        ''
    ]

    topModules = manifests.filter (m) ->
        m.assets?.structure?.placement == 'top'

    for m in topModules
        lines.push "include ../#{m._dir}/#{m.assets.structure.file}"

    return lines.join('\n') + '\n'

# Copy worker files from node_modules to public
copyWorkers = (manifests, dryRun) ->
    copied = []

    for m in manifests when m.assets?.workers
        for worker in m.assets.workers
            srcPath = path.join(CONFIG.projectRoot, 'node_modules', worker.npm)
            destPath = path.join(CONFIG.projectRoot, CONFIG.publicDir, worker.dest)

            unless fs.existsSync(srcPath)
                console.warn "Warning: Worker source not found: #{srcPath}"
                continue

            if dryRun
                console.log "Would copy: #{worker.npm} -> #{worker.dest}"
            else
                ensureDir(path.dirname(destPath))
                fs.copyFileSync(srcPath, destPath)
                console.log "Copied: #{worker.npm} -> #{worker.dest}"

            copied.push({ src: worker.npm, dest: worker.dest, module: m.name })

    return copied

#endregion

############################################################
#region Main

main = ->
    dryRun = process.argv.includes('--dry-run')

    if dryRun
        console.log "=== DRY RUN MODE ==="
        console.log ""

    console.log "Scanning for module manifests..."
    manifests = findManifests()
    console.log "Found #{manifests.length} modules with manifests:"
    for m in manifests
        console.log "  - #{m.name}"
    console.log ""

    # Generate styles
    stylesContent = generateStyles(manifests)
    stylesPath = path.join(CONFIG.projectRoot, CONFIG.outputDir, 'allstyles.styl')
    if dryRun
        console.log "Would write allstyles.styl:"
        console.log stylesContent
    else
        fs.writeFileSync(stylesPath, stylesContent)
        console.log "Generated: #{stylesPath}"

    # Generate structure includes
    structureContent = generateStructure(manifests)
    structurePath = path.join(CONFIG.projectRoot, CONFIG.indexDir, '_auto-includes.pug')
    if dryRun
        console.log "Would write _auto-includes.pug:"
        console.log structureContent
    else
        fs.writeFileSync(structurePath, structureContent)
        console.log "Generated: #{structurePath}"

    # Copy workers
    console.log ""
    console.log "Processing workers..."
    copyWorkers(manifests, dryRun)

    console.log ""
    console.log "Done!"

# Run
main()

#endregion
